// /*
//  * This Java source file was generated by the Gradle 'init' task.
//  */
package pertemuan_9;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.stage.Stage;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.text.Font;
import javafx.scene.control.TextField;
import javafx.scene.control.Label;
import javafx.scene.control.Button;
import javafx.scene.layout.VBox;
import javafx.scene.layout.HBox;

public class Assignment_9_1 extends Application {
    private Stage stage;

    @Override
    public void start(Stage primaryStage) throws Exception {
        primaryStage.setTitle("Kalkulator Club");
        stage = primaryStage;
        showScene1();
        stage.show();
    }

    public void showScene1() {
        Image logo = new Image("/calculator.jpeg");
        ImageView logoView = new ImageView(logo);
        logoView.setFitWidth(100);
        logoView.setFitHeight(100);

        Label label = new Label("Kalkulator Club");
        label.setFont(Font.font("Cambria", 25));

        Button button = new Button("Mulai");
        button.setStyle("-fx-background-color: #E9967A");
        button.setOnAction(action -> {
            showScene2();
        });

        VBox vbox = new VBox(logoView, label, button);
        vbox.setAlignment(Pos.CENTER);
        vbox.setSpacing(15);

        Scene scene = new Scene(vbox, 300, 400);
        stage.setScene(scene);
    }

    public void showScene2() {
        Label label = new Label("Pilih Menu");
        label.setFont(Font.font("Cambria", 25));

        Button kSuhu = new Button("Kalkulator Konversi Suhu");
        kSuhu.setStyle("-fx-background-color: #FFE4B5");
        kSuhu.setOnAction(action -> {
            showKSuhuScene();
        });

        Button trigonometri = new Button("Kalkulator Trigonometri");
        trigonometri.setStyle("-fx-background-color: #FFA07A");
        trigonometri.setOnAction(action -> {
            showCalTrigonometri();   
        });

        Button basicArithmetic = new Button("Kalkulator Aritmatik Dasar");
        basicArithmetic.setStyle("-fx-background-color: #F4A460");
        basicArithmetic.setOnAction(action -> {
            showCalBasicArtihmetic();
        });

        VBox vbox = new VBox(label, kSuhu, trigonometri, basicArithmetic);
        vbox.setAlignment(Pos.TOP_CENTER);
        vbox.setSpacing(15);

        Scene scene = new Scene(vbox, 300, 400);
        stage.setScene(scene);
    }

    public void showKSuhuScene() {
        Label label = new Label("Konversi Suhu");
        label.setFont(Font.font("Cambria",25));

        Button konversiCF = new Button("Celcius ke Fahrenheit");
        konversiCF.setStyle("-fx-background-color: #FFDAB9");
        konversiCF.setOnAction(action -> {
            showCF();
        });

        Button konversiCK = new Button("Celcius ke Kelvin");
        konversiCK.setStyle("-fx-background-color: #FFEFD5");
        konversiCK.setOnAction(action -> {
            showCK();
        });

        Button konversiFC = new Button("Fahrenheit ke Celcius");
        konversiFC.setStyle("-fx-background-color: #FFDAB9");
        konversiFC.setOnAction(action -> {
            showFC();
        });

        Button konversiFK = new Button("Fahrenheit ke Kelvin");
        konversiFK.setStyle("-fx-background-color: #FFEFD5");
        konversiFK.setOnAction(action -> {
            showFK();
        });

        Button konversiKC = new Button("Kelvin ke Celcius");
        konversiKC.setStyle("-fx-background-color: #FFDAB9");
        konversiKC.setOnAction(action -> {
            showKC();
        });

        Button konversiKF = new Button("Kelvin ke Fahrenheit");
        konversiKF.setStyle("-fx-background-color: #FFEFD5");
        konversiKF.setOnAction(action -> {
            showKF();
        });

        Button back = new Button("Back to Pilih Menu");
        back.setStyle("-fx-background-color: #8FBC8F");
        back.setOnAction(action -> {
            showScene2();
        });

        VBox vbox = new VBox(label, konversiCF, konversiCK, konversiFC, konversiFK, konversiKC, konversiKF, back);
        vbox.setAlignment(Pos.TOP_CENTER);
        vbox.setSpacing(15);

        Scene scene = new Scene(vbox, 300, 400);
        stage.setScene(scene);
    }

    public void showCF() {
        Label label = new Label("Konversi Celcius ke Fahrenheit");
        label.setFont(Font.font("Cambria", 20));

        Label label2 = new Label("Masukkan angka :");
        TextField input = new TextField();
        
        Label output = new Label();

        Button konversi = new Button("Konversi");
        konversi.setOnAction(action -> {
            try {
                double celcius = Double.parseDouble(input.getText());
                double hasil = celcius * 9/5 + 32;
                output.setText("Hasil konversi Celcius ke Fahrenheit : " + hasil);
            } catch (NumberFormatException e) {
                output.setText("Inputan bukan angka");
            }
        });

        Button clear = new Button("Clear");
        clear.setStyle("-fx-background-color: #B0C4DE");
        clear.setOnAction(action -> {
            input.setText("");
            output.setText("");
        });

        Button back = new Button("Back to Konversi Suhu");
        back.setStyle("-fx-background-color: #8FBC8F");
        back.setOnAction(action -> {
            showKSuhuScene();
        });

        VBox vbox = new VBox(label, label2, input, output, konversi, clear, back);
        vbox.setAlignment(Pos.CENTER);
        vbox.setSpacing(5);

        Scene scene = new Scene(vbox, 300, 400);
        stage.setScene(scene);
    }

    public void showCK() {
        Label label = new Label("Konversi Celcius ke Kelvin");
        label.setFont(Font.font("Cambria", 20));

        Label label2 = new Label("Masukkan angka :");
        TextField input = new TextField();
        
        Label output = new Label();

        Button konversi = new Button("Konversi");
        konversi.setOnAction(action -> {
            try {
                double celcius = Double.parseDouble(input.getText());
                double hasil = celcius + 273.15;;
                output.setText("Hasil konversi Celcius ke Kelvin : " + hasil);
            } catch (NumberFormatException e) {
                output.setText("Inputan bukan angka");
            }
        });

        Button clear = new Button("Clear");
        clear.setStyle("-fx-background-color: #B0C4DE");
        clear.setOnAction(action -> {
            input.setText("");
            output.setText("");
        });

        Button back = new Button("Back to Konversi Suhu");
        back.setStyle("-fx-background-color: #8FBC8F");
        back.setOnAction(action -> {
            showKSuhuScene();
        });

        VBox vbox = new VBox(label, label2, input, output, konversi, clear, back);
        vbox.setAlignment(Pos.CENTER);
        vbox.setSpacing(5);

        Scene scene = new Scene(vbox, 300, 400);
        stage.setScene(scene);
    }

    public void showFC() {
        Label label = new Label("Konversi Fahrenheit ke Celcius");
        label.setFont(Font.font("Cambria", 20));

        Label label2 = new Label("Masukkan angka :");
        TextField input = new TextField();
        
        Label output = new Label();

        Button konversi = new Button("Konversi");
        konversi.setOnAction(action -> {
            try {
                double fahrenheit = Double.parseDouble(input.getText());
                double hasil = (fahrenheit - 32) * 5/9;
                output.setText("Hasil konversi Fahrenheit ke Celcius : " + hasil);
            } catch (NumberFormatException e) {
                output.setText("Inputan bukan angka");
            }
        });

        Button clear = new Button("Clear");
        clear.setStyle("-fx-background-color: #B0C4DE");
        clear.setOnAction(action -> {
            input.setText("");
            output.setText("");
        });

        Button back = new Button("Back to Konversi Suhu");
        back.setStyle("-fx-background-color: #8FBC8F");
        back.setOnAction(action -> {
            showKSuhuScene();
        });

        VBox vbox = new VBox(label, label2, input, output, konversi, clear, back);
        vbox.setAlignment(Pos.CENTER);
        vbox.setSpacing(5);

        Scene scene = new Scene(vbox, 300, 400);
        stage.setScene(scene);
    }

    public void showFK() {
        Label label = new Label("Konversi Fahrenheit ke Kelvin");
        label.setFont(Font.font("Cambria", 20));

        Label label2 = new Label("Masukkan angka :");
        TextField input = new TextField();
        
        Label output = new Label();

        Button konversi = new Button("Konversi");
        konversi.setOnAction(action -> {
            try {
                double fahrenheit = Double.parseDouble(input.getText());
                double hasil = (fahrenheit - 32) * 5/9 + 273.15;
                output.setText("Hasil konversi Fahrenheit ke Kelvin : " + hasil);
            } catch (NumberFormatException e) {
                output.setText("Inputan bukan angka");
            }
        });

        Button clear = new Button("Clear");
        clear.setStyle("-fx-background-color: #B0C4DE");
        clear.setOnAction(action -> {
            input.setText("");
            output.setText("");
        });

        Button back = new Button("Back to Konversi Suhu");
        back.setStyle("-fx-background-color: #8FBC8F");
        back.setOnAction(action -> {
            showKSuhuScene();
        });

        VBox vbox = new VBox(label, label2, input, output, konversi, clear, back);
        vbox.setAlignment(Pos.CENTER);
        vbox.setSpacing(5);

        Scene scene = new Scene(vbox, 300, 400);
        stage.setScene(scene);
    }

    public void showKC() {
        Label label = new Label("Konversi Kelvin ke Celcius");
        label.setFont(Font.font("Cambria", 20));

        Label label2 = new Label("Masukkan angka :");
        TextField input = new TextField();
        
        Label output = new Label();

        Button konversi = new Button("Konversi");
        konversi.setOnAction(action -> {
            try {
                double kelvin = Double.parseDouble(input.getText());
                double hasil = kelvin - 273.15;
                output.setText("Hasil konversi Kelvin ke Celcius : " + hasil);
            } catch (NumberFormatException e) {
                output.setText("Inputan bukan angka");
            }
        });

        Button clear = new Button("Clear");
        clear.setStyle("-fx-background-color: #B0C4DE");
        clear.setOnAction(action -> {
            input.setText("");
            output.setText("");
        });

        Button back = new Button("Back to Konversi Suhu");
        back.setStyle("-fx-background-color: #8FBC8F");
        back.setOnAction(action -> {
            showKSuhuScene();
        });

        VBox vbox = new VBox(label, label2, input, output, konversi, clear, back);
        vbox.setAlignment(Pos.CENTER);
        vbox.setSpacing(5);

        Scene scene = new Scene(vbox, 300, 400);
        stage.setScene(scene);
    }

    public void showKF() {
        Label label = new Label("Konversi Kelvin ke Fahrenheit");
        label.setFont(Font.font("Cambria", 20));

        Label label2 = new Label("Masukkan angka :");
        TextField input = new TextField();
        
        Label output = new Label();

        Button konversi = new Button("Konversi");
        konversi.setOnAction(action -> {
            try {
                double kelvin = Double.parseDouble(input.getText());
                double hasil = (kelvin - 273.15) * 9/5 + 32;
                output.setText("Hasil konversi Kelvin ke Fahrenheit : " + hasil);
            } catch (NumberFormatException e) {
                output.setText("Inputan bukan angka");
            }
        });

        Button clear = new Button("Clear");
        clear.setStyle("-fx-background-color: #B0C4DE");
        clear.setOnAction(action -> {
            input.setText("");
            output.setText("");
        });

        Button back = new Button("Back to Konversi Suhu");
        back.setStyle("-fx-background-color: #8FBC8F");
        back.setOnAction(action -> {
            showKSuhuScene();
        });

        VBox vbox = new VBox(label, label2, input, output, konversi, clear, back);
        vbox.setAlignment(Pos.CENTER);
        vbox.setSpacing(5);

        Scene scene = new Scene(vbox, 300, 400);
        stage.setScene(scene);
    }

    public void showCalTrigonometri() {
        Label label1 = new Label("Trigonometri");
        label1.setFont(Font.font("Cambria", 25));

        Label label2 = new Label("Masukkan angka :");
        TextField input = new TextField();

        Label output = new Label();

        Button sin = new Button("Sin");
        sin.setOnAction(action -> {
            try{
                double derajat = Double.parseDouble(input.getText());
                double radian = Math.toRadians(derajat);
                double hasil = Math.sin(radian);
                output.setText("Hasil sin = " + hasil);
            } catch(NumberFormatException e) {
                output.setText("Inputan bukan angka");
            }
        });

        Button cos = new Button("Cos");
        cos.setOnAction(action -> {
            try {
                double derajat = Double.parseDouble(input.getText());
                double radian = Math.toRadians(derajat);
                double hasil = Math.cos(radian);
                output.setText("Hasil  cos = " + hasil);
            } catch(NumberFormatException e) {
                output.setText("Inputan bukan angka");
            }
        });

        Button tan = new Button("Tan");
        tan.setOnAction(action -> {
            try {
                double derajat = Double.parseDouble(input.getText());
                double radian = Math.toRadians(derajat);
                double hasil = Math.tan(radian);
                output.setText("Hasil tan = " + hasil);
            } catch(NumberFormatException e) {
                output.setText("Inputan bukan angka");
            }
        });

        HBox sinCosTan = new HBox(sin, cos, tan);
        sinCosTan.setAlignment(Pos.CENTER);
        sinCosTan.setSpacing(5);

        Button clear = new Button("Clear");
        clear.setStyle("-fx-background-color: #B0C4DE");
        clear.setOnAction(action -> {
            input.setText("");
            output.setText("");
        });

        Button back = new Button("Back to Pilih Menu");
        back.setStyle("-fx-background-color: #8FBC8F");
        back.setOnAction(action -> {
            showScene2();
        });

        VBox vbox = new VBox(label1, label2, input, output, sinCosTan, clear, back);
        vbox.setAlignment(Pos.CENTER);
        vbox.setSpacing(15);

        Scene scene = new Scene(vbox, 300, 400);
        stage.setScene(scene);
    }

    public void showCalBasicArtihmetic() {
        Label label = new Label("Aritmatik Dasar");
        label.setFont(Font.font("Cambria", 25));

        TextField input1 = new TextField();
        input1.setPromptText("Input angka");

        TextField input2 = new TextField();
        input2.setPromptText("Input angka");

        Label output = new Label();

        Button kali = new Button("x");
        kali.setOnAction(action -> {
            try {
                double angka1 = Double.parseDouble(input1.getText());
                double angka2 = Double.parseDouble(input2.getText());
                double hasil = angka1 * angka2;
                output.setText("Hasil kali = " + hasil);
            } catch(NumberFormatException e) {
                output.setText("Inputan bukan angka");
            }
        });

        Button bagi = new Button("/");
        bagi.setOnAction(action -> {
            try {
                double angka1 = Double.parseDouble(input1.getText());
                double angka2 = Double.parseDouble(input2.getText());
                double hasil = (double) angka1 / angka2;
                output.setText("Hasil bagi = " + hasil);
            } catch(NumberFormatException e) {
                output.setText("Inputan bukan angka");
            }
        });

        HBox kaliBagi = new HBox(kali, bagi);
        kaliBagi.setAlignment(Pos.CENTER);
        kaliBagi.setSpacing(10);

        Button tambah = new Button("+");
        tambah.setOnAction(action -> {
            try {
                double angka1 = Double.parseDouble(input1.getText());
                double angka2 = Double.parseDouble(input2.getText());
                double hasil = angka1 + angka2;
                output.setText("Hasil tambah = " + hasil);
            } catch(NumberFormatException e) {
                output.setText("Inputan bukan angka");
            }
        });

        Button kurang = new Button("-");
        kurang.setOnAction(action -> {
            try {
                double angka1 = Double.parseDouble(input1.getText());
                double angka2 = Double.parseDouble(input2.getText());
                double hasil = angka1 - angka2;
                output.setText("Hasil kurang = " + hasil);
            } catch(NumberFormatException e) {
                output.setText("Inputan bukan angka");
            }
        });

        HBox tambahKurang = new HBox(tambah, kurang);
        tambahKurang.setAlignment(Pos.CENTER);
        tambahKurang.setSpacing(10);

        VBox kaliBaTaKu = new VBox(kaliBagi, tambahKurang);
        kaliBaTaKu.setAlignment(Pos.CENTER);
        kaliBaTaKu.setSpacing(10);

        Button clear = new Button("Clear");
        clear.setStyle("-fx-background-color: #B0C4DE");
        clear.setOnAction(action -> {
            input1.setText("");
            input2.setText("");
            output.setText("");
        });

        Button back = new Button("Back to Pilih Menu");
        back.setStyle("-fx-background-color: #8FBC8F");
        back.setOnAction(action -> {
            showScene2();
        });

        VBox vbox = new VBox(label, input1, input2, output, kaliBaTaKu, clear, back);
        vbox.setAlignment(Pos.CENTER);
        vbox.setSpacing(15);

        Scene scene = new Scene(vbox, 300, 400);
        stage.setScene(scene);
    }

    public static void main(String[] args) {
        Application.launch(args);
    }
}