/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class App extends Application {
    private static Stage primaryStage;
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        Image image1 = new Image("image/logo.jpg");
        ImageView viewImage1 = new ImageView(image1);
        viewImage1.setFitWidth(150);
        viewImage1.setFitHeight(150);

        Text text1 = new Text("CALCULATOR");
        text1.setFont(Font.font("Arial Black", 20));
        text1.setFill(Color.SKYBLUE);

        Button button1 = new Button("MULAI");
        button1.setStyle("-fx-background-color: skyblue; -fx-text-fill: black;");
        button1.setOnAction(v -> sceneTwo());

        VBox vbox = new VBox(10, viewImage1, text1, button1);
        vbox.setAlignment(Pos.CENTER);
        vbox.setStyle("-fx-background-color: black;");
        
        Scene scene = new Scene(vbox, 350, 400);
        
        App.primaryStage = primaryStage;
        primaryStage.setScene(scene);
        primaryStage.setTitle("CalculatorApp");
        primaryStage.getIcons().add(image1);
        primaryStage.show();
    }
    
    public static void sceneTwo() {
        Text text2 = new Text("PILIH MENU");
        text2.setFont(Font.font("Arial Black", 20));
        text2.setFill(Color.WHITE);

        Button button2 = new Button("TIME");
        button2.setStyle("-fx-background-color: skyblue; -fx-text-fill: black;");
        button2.setOnAction(v -> {
            TimeScene timeScene = new TimeScene(primaryStage);
            timeScene.timeScene();
        });
        Button button3 = new Button("TEMPERATURE");
        button3.setStyle("-fx-background-color: skyblue; -fx-text-fill: black;");
        button3.setOnAction(v -> {
            TemperatureScene temperaturScene = new TemperatureScene(primaryStage);
            temperaturScene.temperatureScene();
        });

        VBox vbox = new VBox(10, text2, button2, button3);
        vbox.setAlignment(Pos.CENTER);
        vbox.setStyle("-fx-background-color: black;");
        
        Scene scene = new Scene(vbox, 350, 400);
        primaryStage.setScene(scene);
        primaryStage.show();
    }
}